export const MainMenu = [
  { label: 'ACCOMMODATIONS', path: '/category/accommodations' },
  { label: 'ATTRACTIONS', path: '/category/attractions' },
  { label: 'DRINK', path: '/category/drink' },
  { label: 'EAT', path: '/category/eat' },
  { label: 'TIPS', path: '/category/tips' },
  { label: 'TOURS & EVENTS', path: '/category/tours-events' },
];
export const SocialMediaLinks = [
  { platform: 'instragram', link: 'https://www.instagram.com/' },
  { platform: 'facebook', link: 'https://www.facebook.com/' },
  { platform: 'tiktok', link: 'https://www.tiktok.com/' },
];

export const Languages = [
  { name: 'English', code: 'en' },
  { name: 'Spanish', code: 'es' },
  { name: '中华人民共和国', code: 'zh-cn' },
  { name: 'French', code: 'fr' },
  { name: 'Arabic', code: 'ar' },
  { name: 'Hindi', code: 'hi' },
  { name: 'Russian', code: 'ru' },
  { name: 'Portuguese', code: 'pt' },
  { name: 'German', code: 'de' },
  { name: 'Brasil', code: 'pt-br' },
  { name: 'Japanese', code: 'ja' },
  { name: 'Malaysian', code: 'ms' },
  { name: 'Thai', code: 'th' },
  { name: 'Indonesian', code: 'id' },
  { name: 'Filipino', code: 'tl' },
  { name: 'Vietnamese', code: 'vi' },
  { name: 'Korean', code: 'ko' },
  { name: 'Bengali', code: 'bn' },
  { name: '台灣', code: 'zh-tw' },
  { name: 'Swedish', code: 'sv' },
  { name: 'Danish', code: 'da' },
  { name: 'Dutch', code: 'nl' },
  { name: 'Italian', code: 'it' },
  { name: 'Norwegian', code: 'no' },
  { name: 'Turkish', code: 'tr' },
  { name: '香港', code: 'zh-hk' },
  { name: 'Farsi/Persian', code: 'fa' },
  { name: 'Polish', code: 'pl' },
  { name: 'Ukrainian', code: 'uk' },
  { name: 'Norwegian', code: 'nb' },
  { name: 'Marathi', code: 'mr' },
  { name: 'Telugu', code: 'te' },
  { name: 'Burmese', code: 'my' },
  { name: 'Sinhala', code: 'si' },
  { name: 'Urdu', code: 'ur' },
  { name: 'Hebrew', code: 'he' },
  { name: 'Hungarian', code: 'hu' },
  { name: 'Swahili', code: 'sw' },
  { name: 'Greek', code: 'el' },
  { name: 'Afrikaans', code: 'af' },
  { name: 'Romanian', code: 'ro' },
  { name: 'Czech', code: 'cs' },
  { name: 'Slovak', code: 'sk' },
  { name: 'Finnish', code: 'fi' },
  { name: 'Serbian', code: 'sr' },
  { name: 'Estonian', code: 'et' },
  { name: 'Hausa', code: 'ha' },
  { name: 'Yoruba', code: 'yo' },
  { name: 'Igbo', code: 'ig' },
  { name: 'Oromo', code: 'om' },
  { name: 'Amharic', code: 'am' },
];